name: Export ALAR

on:
  push:
    branches: [ master ]
  # pull_request:
  #  branches: [ master ]
  schedule:
    # every saturday at 19:00
    - cron: "0 19 * * 6"

jobs:
    deploy:
        name: Deploy
        uses: ./.github/workflows/fullExport.yml
        with:
            environment: alar